language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t client:dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client:dev npm run test -- --coverage

after_success:
  - docker run -t client:prod ./client
  - docker run -t nginx:prod ./nginx
  - docker run -t server:prod ./server
  - docker run -t worker:prod ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push client:prod
  - docker push nginx:prod
  - docker push server:prod
  - docker push worker:prod

